apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://storage.googleapis.com/tekton-releases/chains/previous/v0.22.0/release.yaml
patches:
- target:
    kind: Deployment
    name: tekton-chains-controller
  patch: |-
    - op: add
      path: /spec/template/metadata/annotations/vault.hashicorp.com~1agent-inject
      value: "true"
    - op: add
      path: /spec/template/metadata/annotations/vault.hashicorp.com~1agent-inject-status
      value: "update"
    - op: add
      path: /spec/template/metadata/annotations/vault.hashicorp.com~1agent-inject-token
      value: "true"
    - op: add
      path: /spec/template/metadata/annotations/vault.hashicorp.com~1template-static-secret-render-interval
      value: "10s"
    - op: add
      path: /spec/template/metadata/annotations/vault.hashicorp.com~1secret-volume-path
      value: "/home/nonroot"
    - op: add
      path: /spec/template/metadata/annotations/vault.hashicorp.com~1role
      value: "tekton-role"
    - op: add
      path: /spec/template/metadata/annotations/vault.hashicorp.com~1agent-run-as-user
      value: "65532"
    - op: add
      path: /spec/template/metadata/annotations/vault.hashicorp.com~1agent-run-as-group
      value: "65532"
    - op: add
      path: /spec/template/metadata/annotations/vault.hashicorp.com~1agent-inject-secret-MONGO_SERVER_URL
      value: "secret/data/tekton/mongodb-creds"
    - op: add
      path: /spec/template/metadata/annotations/vault.hashicorp.com~1agent-inject-template-MONGO_SERVER_URL
      value: |
        {{- with secret "secret/data/tekton/mongodb-creds" -}}
        mongodb://{{ .Data.data.username }}:{{ .Data.data.password }}@mongodb-0.mongodb-svc.mongodb.svc.cluster.local:27017/?authSource=admin&replicaSet=mongodb
        {{- end -}}
    - op: add
      path: /spec/template/metadata/annotations/vault.hashicorp.com~1preserve-secret-case
      value: "true"
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: HOME
        value: /home/nonroot
    - op: add
      path: /spec/template/spec/containers/0/securityContext
      value:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
        runAsGroup: 65532
        runAsNonRoot: true
        runAsUser: 65532
        seccompProfile:
          type: RuntimeDefault
- target:
    kind: ConfigMap
    name: chains-config
  patch: |-
    - op: add
      path: /data
      value:
        artifacts.oci.signer: kms
        artifacts.taskrun.signer: kms
        artifacts.taskrun.format: in-toto
        signers.kms.auth.token-path: /home/nonroot/token
        signers.kms.kmsref: "hashivault://tekton-key"
        signers.kms.auth.address: "http://vault.vault:8200"
        artifacts.oci.storage: oci,docdb
        artifacts.taskrun.storage: oci,docdb
        storage.docdb.url: mongo://tekton-chains/bar?id_field=name
        storage.docdb.mongo-server-url-dir: /home/nonroot
- target:
    kind: ServiceAccount
  patch: |-
    - op: add
      path: /imagePullSecrets
      value: [{name: regcred}]
secretGenerator:
- files:
  - .dockerconfigjson=config.json
  name: regcred
  namespace: tekton-chains
  type: kubernetes.io/dockerconfigjson
generatorOptions:
  disableNameSuffixHash: true
